version: '3.8'

services:
  crypto-monitor:
    build:
      context: ./crypto-monitor
      dockerfile: Dockerfile
    image: crypto-monitor:latest
    container_name: crypto-monitor-service
    environment:
      - TZ=Asia/Seoul
      - UPDATE_INTERVAL=30
    volumes:
      - shared-html:/shared
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "test", "-f", "/shared/index.html"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - crypto-network

  nginx:
    image: nginx:alpine
    container_name: crypto-web-server
    ports:
      - "3010:80"
    volumes:
      - shared-html:/usr/share/nginx/html:ro
    depends_on:
      - crypto-monitor
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - crypto-network

volumes:
  shared-html:
    driver: local

networks:
  crypto-network:
    driver: bridge